### ISSUE TITLE
 The given key was not present in the dictionary - Userpool

### ISSUE THREAD

**Issue by GrantBartlett** [SirCmpwn/ChatSharp#50]
Hi

I get this:
	An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in ChatSharp.dll
	Additional information: The given key was not present in the dictionary.

When using this:

	var test = client.Channels[channelName].Users;
	Console.WriteLine(test);	

Why? The channel name is the same I use to connect with. What's the issue?

More:

	System.Collections.Generic.KeyNotFoundException was unhandled
  	HResult=-2146232969
  	Message=The given key was not present in the dictionary.
  	Source=ChatSharp
  	StackTrace:
       at ChatSharp.ChannelCollection.get_Item(String name) in d:\Work\Open Source\ChatSharp\ChatSharp\ChannelCollection.cs:line 56
       at CnCNetClientYR.MainLobby..ctor() in C:\Users\Grant\Documents\Visual Studio 2015\Projects\CnCNetClientYR\CnCNetClientYR\MainLobby.cs:line 21
       at CnCNetClientYR.Program.Main() in C:\Users\Grant\Documents\Visual Studio 2015\Projects\CnCNetClientYR\CnCNetClientYR\Program.cs:line 17
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()

`

**Comment by SirCmpwn** [comment]
Show more of your code. How are you connecting and joining the channel?

**Comment by GrantBartlett** [comment]
I had other code, but just stuck it in the example code from the readme and still same result:

            var client = new IrcClient("irc.freenode.org", new IrcUser("ga-sdk", "ga-sdk"));
            var channelName = "#example";

            client.ConnectionComplete += (s, e) =>
            {
                client.JoinChannel(channelName);

                var test = client.Channels[channelName].Users;
                Console.WriteLine(test);
            };

            client.ChannelMessageRecieved += (s, e) =>
            {
                var channel = client.Channels[e.PrivateMessage.Source];

                if (e.PrivateMessage.Message == ".list")
                    channel.SendMessage(string.Join(", ", channel.Users.Select(u => u.Nick)));
                else if (e.PrivateMessage.Message.StartsWith(".ban "))
                {
                    if (!channel.UsersByMode['@'].Contains(client.User))
                    {
                        channel.SendMessage("I'm not an op here!");
                        return;
                    }
                    var target = e.PrivateMessage.Message.Substring(5);

                }
            };

            client.ConnectAsync();

**Comment by SirCmpwn** [comment]
Join channel is asyncronous. You have to wait until you get the `ChannelListReceived` callback to be considered fully joined to the channel.
